from uuid import uuid4

import pytest
from sqlalchemy import delete

from busirag.db.models import Chunk, Document, Tenant
from busirag.db.session import SessionLocal
import busirag.retrieval.hybrid as hybrid_module
import busirag.retrieval.modes as modes_module
from busirag.retrieval.hybrid import retrieve_hybrid_chunks
from busirag.retrieval.modes import RETRIEVAL_MODES, retrieve_chunks
from busirag.retrieval.sparse import (
    SparseRetrievalResult,
    retrieve_sparse_chunks,
)
from busirag.retrieval.vector import RetrievalResult


def test_retrieval_modes_are_the_documented_four():
    assert RETRIEVAL_MODES == (
        "dense",
        "sparse",
        "hybrid",
        "hybrid_rerank",
    )


@pytest.mark.parametrize(
    ("mode", "function_name"),
    [
        ("dense", "retrieve_similar_chunks"),
        ("sparse", "retrieve_sparse_chunks"),
        ("hybrid", "retrieve_hybrid_chunks"),
        ("hybrid_rerank", "retrieve_reranked_chunks"),
    ],
)
def test_retrieve_chunks_dispatches_by_mode(
    monkeypatch,
    mode,
    function_name,
):
    calls = []

    for name in (
        "retrieve_similar_chunks",
        "retrieve_sparse_chunks",
        "retrieve_hybrid_chunks",
        "retrieve_reranked_chunks",
    ):
        monkeypatch.setattr(
            modes_module,
            name,
            lambda _name=name, **kwargs: calls.append(
                (_name, kwargs)
            ) or [],
        )

    retrieve_chunks(
        mode=mode,
        session=None,
        query="q",
        tenant_id=1,
        embedding_provider=object(),
        reranker=object(),
        top_k=7,
        candidate_k=30,
    )

    assert [name for name, _ in calls] == [function_name]
    assert calls[0][1]["top_k"] == 7
    assert calls[0][1]["tenant_id"] == 1


def test_retrieve_chunks_rejects_unknown_mode():
    with pytest.raises(ValueError, match="Unknown retrieval mode"):
        retrieve_chunks(
            mode="bm25",
            session=None,
            query="q",
            tenant_id=1,
        )


def test_hybrid_rerank_requires_reranker():
    with pytest.raises(ValueError, match="requires a reranker"):
        retrieve_chunks(
            mode="hybrid_rerank",
            session=None,
            query="q",
            tenant_id=1,
        )


def _dense(chunk_id):
    return RetrievalResult(
        chunk_id=chunk_id,
        document_id=1,
        text=f"dense {chunk_id}",
        company="apple",
        filename="apple-2023.pdf",
        year=2023,
        page_number=1,
        section=None,
        element_type="text",
        similarity=0.9,
    )


def _sparse(chunk_id):
    return SparseRetrievalResult(
        chunk_id=chunk_id,
        document_id=1,
        text=f"sparse {chunk_id}",
        company="apple",
        filename="apple-2023.pdf",
        year=2023,
        page_number=2,
        section=None,
        element_type="table",
        score=0.5,
    )


def test_hybrid_fuses_sparse_only_candidates(monkeypatch):
    monkeypatch.setattr(
        hybrid_module,
        "retrieve_similar_chunks",
        lambda **kwargs: [_dense(1), _dense(2)],
    )
    monkeypatch.setattr(
        hybrid_module,
        "retrieve_sparse_chunks",
        lambda **kwargs: [_sparse(2), _sparse(3)],
    )

    results = retrieve_hybrid_chunks(
        session=None,
        query="q",
        embedding_provider=object(),
        tenant_id=1,
        top_k=3,
    )

    # Chunk 2 is found by both retrievers, so RRF ranks it first.
    assert [result.chunk_id for result in results] == [2, 1, 3]
    assert results[2].filename == "apple-2023.pdf"
    assert results[2].element_type == "table"


def test_sparse_retrieval_indexes_newly_inserted_chunks():
    """
    search_vector is generated by Postgres, so a chunk inserted
    without setting it is still found by full-text search.
    """

    marker = f"zqxmarker{uuid4().hex[:12]}"

    with SessionLocal() as session:
        tenant = Tenant(name=f"sparse-test-{uuid4().hex}")
        session.add(tenant)
        session.flush()

        document = Document(
            tenant_id=tenant.id,
            company="acme",
            year=2024,
            filename="acme-2024.pdf",
            source_path="/tmp/acme-2024.pdf",
            content_hash=uuid4().hex,
            chunking_version="test",
            embedding_model="test",
        )
        session.add(document)
        session.flush()

        session.add(
            Chunk(
                document_id=document.id,
                chunk_index=0,
                text=f"Acme operating income rose sharply {marker}",
                element_type="text",
                token_count=6,
                content_hash=uuid4().hex,
                embedding=[0.0] * 384,
                chunking_version="test",
                embedding_model="test",
            )
        )
        session.commit()

        try:
            results = retrieve_sparse_chunks(
                session=session,
                query=f"operating income {marker}",
                tenant_id=tenant.id,
            )

            assert len(results) == 1
            assert results[0].filename == "acme-2024.pdf"
            assert results[0].company == "acme"
        finally:
            session.execute(
                delete(Document).where(Document.id == document.id)
            )
            session.execute(
                delete(Tenant).where(Tenant.id == tenant.id)
            )
            session.commit()
