"""version document identity

Revision ID: 1c38ba154912
Revises: 68e602c1a302
Create Date: 2026-09-03 20:12:00.262612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c38ba154912'
down_revision: Union[str, Sequence[str], None] = '68e602c1a302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('documents_content_hash_key'), 'documents', type_='unique')
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_unique_constraint('uq_document_pipeline_version', 'documents', ['content_hash', 'chunking_version', 'embedding_model'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_pipeline_version', 'documents', type_='unique')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.create_unique_constraint(op.f('documents_content_hash_key'), 'documents', ['content_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
