"""add pipeline versioning

Revision ID: 68e602c1a302
Revises: 7bd48d82e67e
Create Date: 2026-09-03 20:06:33.225227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e602c1a302'
down_revision: Union[str, Sequence[str], None] = '7bd48d82e67e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'documents',
        sa.Column('chunking_version', sa.String(length=50), nullable=True)
    )

    op.add_column(
        'documents',
        sa.Column('embedding_model', sa.String(length=255), nullable=True)
    )

    op.add_column(
        'chunks',
        sa.Column('chunking_version', sa.String(length=50), nullable=True)
    )

    op.add_column(
        'chunks',
        sa.Column('embedding_model', sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###

    op.execute(
        "UPDATE documents "
        "SET chunking_version = 'legacy', "
        "embedding_model = 'BAAI/bge-small-en-v1.5'"
    )

    op.execute(
        "UPDATE chunks "
        "SET chunking_version = 'legacy', "
        "embedding_model = 'BAAI/bge-small-en-v1.5'"
    )

    op.alter_column(
        'documents',
        'chunking_version',
        existing_type=sa.String(length=50),
        nullable=False,
    )

    op.alter_column(
        'documents',
        'embedding_model',
        existing_type=sa.String(length=255),
        nullable=False,
    )

    op.alter_column(
        'chunks',
        'chunking_version',
        existing_type=sa.String(length=50),
        nullable=False,
    )

    op.alter_column(
        'chunks',
        'embedding_model',
        existing_type=sa.String(length=255),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'embedding_model')
    op.drop_column('documents', 'chunking_version')
    op.drop_column('chunks', 'embedding_model')
    op.drop_column('chunks', 'chunking_version')
    # ### end Alembic commands ###
